update deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -3,7 +3,7 @@
 help() {
 	echo "deploy [OPTIONS]"
 	echo "    -h        Prints help"
-	echo "    -v ARG    Specifies gem version (required)"
+	echo "    -v ARG    Specifies gem version"
 	exit 0
 }
 
@@ -29,18 +29,18 @@ while true; do
 		-- )
 			# shift
 			# break
-    		echo "Option -h or -v required"
-    		exit 1
+			echo "Option -h or -v required"
+			exit 1
 			;;
     	* )
-    		echo "Unknown option: $1"
-    		exit 1
-    		;;
+			echo "Unknown option: $1"
+			exit 1
+			;;
 	esac
 	shift
 done
 
 if [ $# -ne 0 ]; then
-  echo "Unknown option(s): $@"
-  exit 1
+	echo "Unknown option(s): $@"
+	exit 1
 fi
